// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDguCI6LjmTCr-34rVPWDxOU9oBgbAfqmw',
    appId: '1:147892159714:web:0e00e036c9bf7f92670abb',
    messagingSenderId: '147892159714',
    projectId: 'classroom-mngnt',
    authDomain: 'classroom-mngnt.firebaseapp.com',
    storageBucket: 'classroom-mngnt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GttUe9PIRJ8DMqZZJblcaK50aETMLKM',
    appId: '1:147892159714:android:e9eecbe8e3dfcbb7670abb',
    messagingSenderId: '147892159714',
    projectId: 'classroom-mngnt',
    storageBucket: 'classroom-mngnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsU_qkq8yjRP6L8TynSfz0y3cgPOEFnsk',
    appId: '1:147892159714:ios:4ed116431925a6c8670abb',
    messagingSenderId: '147892159714',
    projectId: 'classroom-mngnt',
    storageBucket: 'classroom-mngnt.firebasestorage.app',
    iosBundleId: 'com.example.classroomManangement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsU_qkq8yjRP6L8TynSfz0y3cgPOEFnsk',
    appId: '1:147892159714:ios:4ed116431925a6c8670abb',
    messagingSenderId: '147892159714',
    projectId: 'classroom-mngnt',
    storageBucket: 'classroom-mngnt.firebasestorage.app',
    iosBundleId: 'com.example.classroomManangement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDguCI6LjmTCr-34rVPWDxOU9oBgbAfqmw',
    appId: '1:147892159714:web:f282167c8e64d878670abb',
    messagingSenderId: '147892159714',
    projectId: 'classroom-mngnt',
    authDomain: 'classroom-mngnt.firebaseapp.com',
    storageBucket: 'classroom-mngnt.firebasestorage.app',
  );
}
